### ISSUE TITLE
option to avoid filling in special cases

### ISSUE THREAD

**Issue by BrianZbr** [davidshepherd7/aggressive-fill-paragraph-mode#18]
When writing in org-mode with biblatex citations I often have strings like this: `\autocites[chapter 2]{some-book}` or whatever. That needs to be on line line, because if there is a line break between `chapter` and `2`, org-mode will not export it correctly. So, I would ideally like `aggressive-fill-paragraph` to treat such strings as single words.

I am assuming this is a special case. Perhaps it would be useful then to have a customizable list variable for regular expressions that should be treated as words, globally or in a specific major mode?

**Comment by davidshepherd7** [comment]
`aggressive-fill-paragraph` basically just calls the major mode's fill paragraph function to do the actual filling (except for a few special cases where the fill is suppressed). So for things like this you just need to make normal filling (i.e. what you get by pressing M-q) work then afp will work as well.

It looks like [this](http://emacs.stackexchange.com/questions/12392/prevent-fill-paragraph-from-breaking-latex-citations-in-org-mode/12419#12419) allows you to specify arbitrary fill-disabling predicates.

**Comment by BrianZbr** [comment]
Will try that, thanks!
