### ISSUE TITLE
Doesn't allow sentences separated by two spaces

### ISSUE THREAD

**Issue by alphapapa** [davidshepherd7/aggressive-fill-paragraph-mode#22]
The convention in Emacs is for sentences to be separated by two spaces (at least, if `sentence-end-double-space` is non-nil, which is the default).  afp doesn't seem to allow this.  If point is at the end of a comment, after a period, it only allows one space to be inserted, so the user must start typing the next sentence and then move back to insert the second space.

**Comment by davidshepherd7** [comment]
Should be fixed now, thanks for pointing that out :+1:

**Comment by alphapapa** [comment]
Great, thanks!  I tried fixing it myself but it was more difficult than expected and I, uh...lost interest at the time... ;)  I see the way you solved it is very elegant.  The only suggestion I have is that it *might* be good to take `sentence-end-double-space` into account, for users who have it disabled.  But I'm happy with this fix!  :D
