### ISSUE TITLE
The ess package does not provide a ess-mode feature

### ISSUE THREAD

**Issue by tarsius** [davidshepherd7/aggressive-fill-paragraph-mode#25]
... but `afp-ess-fill-comments` `require`s it.

**Comment by davidshepherd7** [comment]
Ah yeah, I think they changed it to just `ess`. For now you can just change it in your local copy and it should work. I'll try to figure out something compatible with both new and older ess versions when I have some time (any ideas?).

**Comment by tarsius** [comment]
I don't use `ess` - I maintain the [Emacsmirror](https://emacsmirror.net) and am currently tracking down [unsatisfied dependencies and other issues](https://emacsmirror.net/stats/issues.html).

> (any ideas?)

```lisp
(or (require (quote ess-mode) nil t)
    (require 'ess))
```

The explicit quote hides the feature from the tools I use to extract dependencies. Feel free to drop that, I can [explicitly hide dependencies](https://emacsmirror.net/stats/kludges.html) as "for backward compatibility only".

**Comment by davidshepherd7** [comment]
That sounds like a good thing to check, thanks for doing it :+1:

And thanks for letting me know about this, I'll try that require snippet when I get a chance.

**Comment by davidshepherd7** [comment]
Those dynamic requires are gone: seems like ess now advises fill-paragraph instead of whatever it used to do so I don't need any special code for R :slightly_smiling_face:

**Comment by tarsius** [comment]
Thanks!
