### ISSUE TITLE
org-mode: table issue when typing a blank space

### ISSUE THREAD

**Issue by manuel-uberti** [davidshepherd7/aggressive-fill-paragraph-mode#6]
I'm using `aggressive-fill-paragraph-mode` in Org and TeX files. In Org files, whenever I am editing a table cell, hitting `SPC` (space bar) puts the cursor at the very first character inside the cell.

I am using Emacs 25.0.50.1 on Debian sid.

**Comment by davidshepherd7** [comment]
Hi, thanks for the report.

It looks like `org-mode` is doing a lot of stuff inside its `fill-paragraph-function`, one of which is to reformat tables. However the cursor isn't put back to the same position after this reformatting (I guess they didn't expect anyone to do something crazy like constantly refilling!)

One workaround that I could implement quite easily would be to not fill-paragraphs if we are inside tables, is that good enough? I don't really use org tables, so I guess what I'm asking is: do people often/ever write paragraphs of text inside a table element?

If not I think we would need to ask the org-mode devs if it's possible to leave the cursor alone when reformatting tables.

Anyway I've pushed a change which disables the aggressive filling when inside a table in org mode. Could you give it a try?

**Comment by davidshepherd7** [comment]
Also does it work well for you in TeX mode? I had some problems with it wrapping latex commands like `\begin{equation}` into paragraphs so I'm not using it for Tex at the moment.

**Comment by manuel-uberti** [comment]
Your latest commit fixed the org-mode table issue, thank you. I'm not writing long paragraphs in table cells, just short lines.

As for TeX mode: I'm not having problem at the moment using your mode with it. I don't use `\begin{equation}` a lot, but I use `\begin{description}` , `\begin{enumerate}` and `\begin{threeparttable}` and everything is working fine.

**Comment by davidshepherd7** [comment]
You're right TeX mode is fine, maybe I was using an older version when I tried it before.
