### ISSUE TITLE
Cannot install via MELPA in emacs 24.3

### ISSUE THREAD

**Issue by BrianZbr** [davidshepherd7/aggressive-fill-paragraph-mode#8]
If I try to install this package from MELPA in Emacs 24.3, I get the message Package `emacs-24.4' is unavailable`. Is emacs 24.4 in fact required? 

The help buffer is telling me that is, but since the readme here doesn't mention that, I'm wondering if there is something going wrong with my setup or something else.

**Comment by davidshepherd7** [comment]
It might work, but I've never tested it. I think I was probably being overly cautious in adding that requirement.

Will Emacs let you install it anyway to try it out?

**Comment by BrianZbr** [comment]
Not via MELPA, it won't. But I just downloaded it from here and gave it a quick try... It seems to work fine! 

So my suggestion would be to remove the requirement from MELPA so it can be installed that way.

**Comment by davidshepherd7** [comment]
That's great, thanks! I've removed the requirement now.
