### ISSUE TITLE
Problem with comments

### ISSUE THREAD

**Issue by BrianZbr** [davidshepherd7/aggressive-fill-paragraph-mode#9]
When `aggressive-fill-paragraph` is enabled, and I am trying to insert a space within a comment,  `comment-forward` will often throw up the error `Wrong type argument: stringp, nil`. Here is the full output from `debug-on-error`.

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  re-search-forward(nil nil move)
  comment-forward(159565)
  comment-only-p(158045 158047)
  (and (comment-only-p (point-at-bol) (point-at-eol)) (string-match-p (concat "^[ ]*" comment-start "[ ]*[-\\*\\+]") (afp-current-line)))
  afp-bullet-list-in-comments\?()
  funcall(afp-bullet-list-in-comments\?)
  -any\?(funcall (afp-markdown-inside-code-block\? afp-bullet-list-in-comments\? afp-in-org-table\?))
  afp-suppress-fill\?()
  (not (afp-suppress-fill\?))
  (if (not (afp-suppress-fill\?)) (progn (funcall (afp-choose-fill-function))))
  afp-fill-then-insert-space()
  call-interactively(afp-fill-then-insert-space nil nil)
```

**Comment by davidshepherd7** [comment]
That seems strange. What version of emacs are you using? Have you got any settings or advice which could affect `comment-only-p`?

**Comment by davidshepherd7** [comment]
Some other things that might help figure the problem out:
- Can you try running `comment-only-p` itself and see if it errors.
- Can you give me an example of a case where the error occurs? Does it occur consistently with the same comment?

**Comment by BrianZbr** [comment]
I'm running Emacs 24.3.1, which is standard for Ubuntu 14.04. 

If I try to evaluate the `comment-only-p` line on its own, it gives `Invalid function: 158045`.

Once it happens, it seems to continue happening anywhere in any comment and in any `org-mode` buffer. Now that I check, it does not seem to affect other modes. If I restart Emacs, the problem goes away for a while. I don't know what triggers it to start happening again, but it does frequently.

**Comment by davidshepherd7** [comment]
Ok, I've pushed a possible fix. Turns out there's a crazy barely documented requirement to call `comment-normalize-vars` before calling `comment-only-p`. Let me know if it helps :)

 I don't know why I've never had this issue, maybe it only affects some modes...

**Comment by BrianZbr** [comment]
Thanks! I will reopen this issue if that doesn't solve it.

**Comment by davidshepherd7** [comment]
Just to check: did the fix work?

**Comment by BrianZbr** [comment]
I just finally updated yesterday, but so far, so good!
